<?php

namespace Database\Seeders;

use App\Models\Contact;
use App\Models\User;
use Illuminate\Database\Seeder;

class ContactSeeder extends Seeder
{
    public function run(): void
    {
        // Lấy tài khoản khách hàng để liên kết một số liên hệ
        $customer = User::where('role', 'customer')->first();
        $customerId = $customer ? $customer->id : null;

        $contacts = [
            [
                'user_id' => $customerId,
                'name' => 'Nguyễn Hoài Nam',
                'email' => 'nam.nguyenhoai@gmail.com',
                'phone' => '0912345678',
                'subject' => 'Hỏi về tình trạng hàng của mẫu Seiko Presage',
                'type' => 'question',
                'message' => 'Shop cho em hỏi mẫu Seiko Presage Automatic còn hàng ở chi nhánh Quận 10 không ạ? Em định qua xem trực tiếp.',
                'status' => 'new',
                'admin_reply' => null,
                'replied_at' => null,
            ],
            [
                'user_id' => null,
                'name' => 'Trần Thị Mai',
                'email' => 'maitran.98@yahoo.com',
                'phone' => '0987654321',
                'subject' => 'Góp ý về sản phẩm mua tại cửa hàng',
                'type' => 'feedback',
                'message' => 'Đồng hồ mua ở shop rất đẹp, đóng gói cẩn thận và giao nhanh. Trải nghiệm rất ưng ý, mình sẽ tiếp tục ủng hộ shop.',
                'status' => 'new',
                'admin_reply' => null,
                'replied_at' => null,
            ],
            [
                'user_id' => $customerId,
                'name' => 'Phạm Hoàng Long',
                'email' => 'longph.dev@gmail.com',
                'phone' => '0909123456',
                'subject' => 'Lỗi cổng thanh toán VNPay',
                'type' => 'report',
                'message' => 'Tôi gặp lỗi khi cố gắng thanh toán bằng VNPay ở bước cuối cùng, hệ thống báo lỗi không giao dịch được. Mong shop hỗ trợ kiểm tra.',
                'status' => 'new',
                'admin_reply' => null,
                'replied_at' => null,
            ],
            [
                'user_id' => null,
                'name' => 'Lê Văn Cường',
                'email' => 'cuongle.partners@outlook.com',
                'phone' => '0933445566',
                'subject' => 'Đề xuất hợp tác kinh doanh làm đại lý',
                'type' => 'other',
                'message' => 'Tôi đang làm chủ một cửa hàng trang sức lớn tại Cần Thơ và muốn đăng ký hợp tác đại lý phân phối các dòng sản phẩm của bên mình, vui lòng liên hệ lại để trao đổi sâu hơn.',
                'status' => 'new',
                'admin_reply' => null,
                'replied_at' => null,
            ],
            [
                'user_id' => null,
                'name' => 'Bùi Thị Hồng',
                'email' => 'hongbui.violet@gmail.com',
                'phone' => '0945889900',
                'subject' => 'Hỏi thông số chống nước Citizen Eco-Drive',
                'type' => 'question',
                'message' => 'Mẫu Citizen Eco-Drive mã CZ-102 bên mình chống nước bao nhiêu mét vậy shop? Đi mưa lớn hay tắm bồn có sao không?',
                'status' => 'read',
                'admin_reply' => null,
                'replied_at' => null,
            ],
            [
                'user_id' => $customerId,
                'name' => 'Đỗ Minh Triết',
                'email' => 'trietdo95@gmail.com',
                'phone' => '0977112233',
                'subject' => 'Phản hồi về thời gian vận chuyển',
                'type' => 'feedback',
                'message' => 'Nhân viên tư vấn nhiệt tình, tuy nhiên đơn hàng giao về Biên Hòa bị chậm hơn dự kiến 1 ngày so với cam kết ban đầu.',
                'status' => 'read',
                'admin_reply' => null,
                'replied_at' => null,
            ],
            [
                'user_id' => null,
                'name' => 'Ngô Thanh Sơn',
                'email' => 'sonngo.arts@gmail.com',
                'phone' => '0966554433',
                'subject' => 'Lỗi hiển thị ảnh trên trang chi tiết Orient Sun and Moon',
                'type' => 'report',
                'message' => 'Tôi thấy hình ảnh sản phẩm Orient Sun and Moon Gen 4 trên website bị lỗi hiển thị, chỉ có ảnh thumbnail mà không xem được thư viện ảnh gallery bên dưới.',
                'status' => 'read',
                'admin_reply' => null,
                'replied_at' => null,
            ],
            [
                'user_id' => $customerId,
                'name' => 'Hoàng Ngọc Anh',
                'email' => 'ngocanh.hoang@gmail.com',
                'phone' => '0955998877',
                'subject' => 'Chính sách trả góp 0%',
                'type' => 'question',
                'message' => 'Shop có hỗ trợ trả góp 0% qua thẻ tín dụng của ngân hàng Techcombank không ạ? Kỳ hạn bao lâu và có mất phí chuyển đổi không?',
                'status' => 'read',
                'admin_reply' => null,
                'replied_at' => null,
            ],
            [
                'user_id' => null,
                'name' => 'Vũ Quốc Trung',
                'email' => 'trungvq.sales@gmail.com',
                'phone' => '0911223344',
                'subject' => 'Hỏi về thời hạn bảo hành chính hãng',
                'type' => 'question',
                'message' => 'Đồng hồ Casio và Orient mua tại cửa hàng bên mình được bảo hành chính hãng trong bao lâu và thủ tục bảo hành thế nào?',
                'status' => 'replied',
                'admin_reply' => 'Chào bạn Trung, tất cả đồng hồ mua tại shop đều được bảo hành chính hãng từ 1 đến 2 năm tùy hãng, đồng thời shop tặng thêm gói bảo hành vàng 5 năm tại cửa hàng bao gồm cả thay pin miễn phí trọn đời nhé!',
                'replied_at' => now()->subHours(5),
            ],
            [
                'user_id' => $customerId,
                'name' => 'Đặng Minh Quân',
                'email' => 'quandm.digital@gmail.com',
                'phone' => '0988009911',
                'subject' => 'Hộp đựng sản phẩm bị móp méo khi vận chuyển',
                'type' => 'report',
                'message' => 'Tôi nhận hàng chiều nay, đồng hồ hoạt động tốt nhưng hộp da bên ngoài bị móp méo góc rất nặng. Vì đây là quà tặng sếp nên trông hơi mất thẩm mỹ.',
                'status' => 'replied',
                'admin_reply' => 'Chào anh Quân, shop vô cùng xin lỗi vì sự cố không mong muốn trong lúc vận chuyển của bên đơn vị giao nhận. Shop đã cho nhân viên gửi hỏa tốc một hộp da Orient mới tinh nguyên vẹn tới địa chỉ của anh hoàn toàn miễn phí rồi ạ. Rất mong anh thông cảm cho cửa hàng!',
                'replied_at' => now()->subHours(12),
            ],
            [
                'user_id' => null,
                'name' => 'Nguyễn Thanh Thủy',
                'email' => 'thuynt.marketing@gmail.com',
                'phone' => '0908889999',
                'subject' => 'Lời khen ngợi dịch vụ gói quà',
                'type' => 'feedback',
                'message' => 'Dịch vụ gói quà tặng của shop rất đẹp và sang trọng! Người nhận quà rất thích. Chúc shop ngày càng đông khách nhé!',
                'status' => 'replied',
                'admin_reply' => 'Cửa hàng Đồng Hồ Online xin chân thành cảm ơn những đánh giá tốt và sự tin tưởng của chị Thủy! Chúc chị và gia đình luôn có những trải nghiệm mua sắm tuyệt vời tại shop.',
                'replied_at' => now()->subHours(20),
            ],
            [
                'user_id' => null,
                'name' => 'Trần Đức Huy',
                'email' => 'huytran.media@yahoo.com',
                'phone' => '0932221100',
                'subject' => 'Đề xuất hợp tác tài trợ sự kiện truyền thông',
                'type' => 'other',
                'message' => 'Chào bộ phận Marketing của Đồng Hồ Online. Chúng tôi là đơn vị tổ chức giải chạy bán marathon tại TPHCM tháng tới, muốn đề xuất gói tài trợ quà tặng đồng hồ thể thao cho giải đấu. Mong nhận được phản hồi qua email.',
                'status' => 'replied',
                'admin_reply' => 'Chào anh Huy, cảm ơn anh đã quan tâm đến thương hiệu của chúng tôi. Bộ phận truyền thông & đối ngoại của shop đã nhận được đề xuất và sẽ chủ động liên hệ lại trực tiếp qua email của anh để thảo luận chi tiết nhé.',
                'replied_at' => now()->subDays(1),
            ],
            [
                'user_id' => $customerId,
                'name' => 'Phạm Văn Minh',
                'email' => 'minhpv.ca@gmail.com',
                'phone' => '0922334455',
                'subject' => 'Hỏi về ship COD tỉnh Cà Mau',
                'type' => 'question',
                'message' => 'Tôi muốn mua chiếc Tissot Luxury nhưng ở huyện Trần Văn Thời, Cà Mau thì shop có giao hàng COD tận nơi và cho kiểm tra hàng không?',
                'status' => 'closed',
                'admin_reply' => 'Chào bạn, shop hỗ trợ giao hàng COD miễn phí trên toàn quốc bao gồm cả Cà Mau nhé. Khi nhận hàng, bạn được quyền mở hộp đồng hồ kiểm tra, đeo thử lên tay, đầy đủ thẻ bảo hành chính hãng và hóa đơn rồi mới thanh toán tiền cho shipper ạ.',
                'replied_at' => now()->subDays(2),
            ],
            [
                'user_id' => null,
                'name' => 'Lê Thị Diễm',
                'email' => 'diemle.hr@gmail.com',
                'phone' => '0919191919',
                'subject' => 'Đồng hồ Casio Edifice chồng rất thích',
                'type' => 'feedback',
                'message' => 'Mình mua tặng sinh nhật chồng chiếc Casio Edifice bên shop, chồng mình thích lắm. Hàng chuẩn chính hãng sờ rất xịn sò.',
                'status' => 'closed',
                'admin_reply' => 'Cảm ơn chị Diễm rất nhiều! Cửa hàng thật vui khi món quà sinh nhật mang lại niềm vui cho anh nhà. Chúc anh chị luôn hạnh phúc và đồng hành cùng shop trong tương lai ạ!',
                'replied_at' => now()->subDays(3),
            ],
            [
                'user_id' => $customerId,
                'name' => 'Nguyễn Quốc Khánh',
                'email' => 'khanhnq.90@gmail.com',
                'phone' => '0944007788',
                'subject' => 'Không áp dụng được mã giảm giá WATCH50',
                'type' => 'report',
                'message' => 'Mã giảm giá WATCH50 công bố trên banner trang chủ nhưng khi tôi nhập ở bước thanh toán hệ thống cứ báo mã không hợp lệ hoặc đã hết lượt.',
                'status' => 'closed',
                'admin_reply' => 'Chào anh Khánh, do lượng người dùng truy cập lớn nên hệ thống kiểm tra mã voucher bị quá tải tạm thời. Lỗi đã được kỹ thuật xử lý xong, shop cũng đã kích hoạt lại mã cho tài khoản của anh rồi ạ. Anh có thể tiến hành đặt mua sản phẩm bình thường.',
                'replied_at' => now()->subDays(4),
            ],
            [
                'user_id' => null,
                'name' => 'Trịnh Đình Khang',
                'email' => 'khangtd.contract@gmail.com',
                'phone' => '0981188229',
                'subject' => 'Đăng ký kích hoạt bảo hành điện tử',
                'type' => 'other',
                'message' => 'Tôi mới mua đồng hồ Seiko tại shop tuần trước nhưng quên chưa kích hoạt bảo hành điện tử online qua tin nhắn SMS, nhờ admin hỗ trợ kích hoạt giúp tôi số serial trên thẻ.',
                'status' => 'closed',
                'admin_reply' => 'Chào anh Khang, shop đã kiểm tra thông tin mua hàng dựa trên số điện thoại và số serial của thẻ. Hệ thống đã kích hoạt thành công chế độ bảo hành vàng cho đồng hồ của anh kể từ ngày mua. Cảm ơn anh!',
                'replied_at' => now()->subDays(5),
            ],
            [
                'user_id' => null,
                'name' => 'Huỳnh Minh Anh',
                'email' => 'minhanh.huynh@gmail.com',
                'phone' => '0979998811',
                'subject' => 'Địa chỉ chi nhánh tại Hà Nội',
                'type' => 'question',
                'message' => 'Shop ơi mình có cửa hàng trưng bày nào ở khu vực Hà Nội không ạ? Mình muốn tới đeo thử xem mặt số 40mm có bị to so với cổ tay không.',
                'status' => 'new',
                'admin_reply' => null,
                'replied_at' => null,
            ],
            [
                'user_id' => $customerId,
                'name' => 'Phan Văn Hậu',
                'email' => 'hauphan.sport@gmail.com',
                'phone' => '0961234567',
                'subject' => 'Giao diện web rất đẹp',
                'type' => 'feedback',
                'message' => 'Giao diện web mới nâng cấp nhìn cực sang xịn mịn, đặc biệt phần gợi ý sản phẩm bằng AI dùng rất thông minh và mượt mà.',
                'status' => 'new',
                'admin_reply' => null,
                'replied_at' => null,
            ],
            [
                'user_id' => null,
                'name' => 'Lý Gia Bảo',
                'email' => 'baoly.arts@outlook.com',
                'phone' => '0901239876',
                'subject' => 'Sai lệch thông số mặt kính Tissot Visodate',
                'type' => 'report',
                'message' => 'Trang thông số kỹ thuật ghi mẫu Tissot Visodate dùng kính cứng Mineral, nhưng theo tôi tìm hiểu chính xác thì dòng này dùng kính Sapphire vòm chống trầy. Shop vui lòng cập nhật lại thông tin.',
                'status' => 'read',
                'admin_reply' => null,
                'replied_at' => null,
            ],
            [
                'user_id' => null,
                'name' => 'Võ Minh Thư',
                'email' => 'thuvo.99@gmail.com',
                'phone' => '0988665544',
                'subject' => 'Giờ mở cửa và đóng cửa của showroom',
                'type' => 'question',
                'message' => 'Shop mở cửa kinh doanh từ mấy giờ sáng đến mấy giờ tối vậy ạ? Buổi tối tầm 9 giờ qua xem thì shop còn mở cửa không?',
                'status' => 'replied',
                'admin_reply' => 'Dạ chào bạn Thư, các showroom trưng bày của cửa hàng mở cửa đón khách từ 8:00 sáng đến 21:30 tối tất cả các ngày trong tuần (kể cả Thứ Bảy và Chủ Nhật). Rất hân hạnh được đón tiếp bạn ghé thăm!',
                'replied_at' => now()->subMinutes(30),
            ],
        ];

        foreach ($contacts as $contactData) {
            Contact::create($contactData);
        }

        $this->command->info('✅ Đã tạo thành công 20 liên hệ (Contact) dữ liệu mẫu với các trạng thái khác nhau!');
    }
}
