FROM richarvey/nginx-php-fpm:3.1.6

COPY . .

# Image config
ENV SKIP_COMPOSER 1
ENV WEBROOT /var/www/html/public
ENV PHP_ERRORS_STDERR 1
ENV RUN_SCRIPTS 1
ENV REAL_IP_HEADER 1
ENV ROOT /var/www/html
ENV PHP_MEM_LIMIT 256
ENV PHP_POST_MAX_SIZE 50
ENV PHP_UPLOAD_MAX_FILESIZE 50
ENV NGINX_MAX_UPLOAD_SIZE 50

CMD ["/start.sh"]
